// base.c
// Convert the number argv[1] to a number base argv[2] for 2<=base<=16
// Usage message  generated by incorrect command-line args
// Uses the quack ADT, compile using 'dcc quack.cc base.c'

#include <stdlib.h>
#include <stdio.h>
#include "quack.h"

#define MAX 16

int main(int argc, char *argv[]) {
   int num, base;

   if ((argc == 3) &&
       (sscanf(argv[1], "%d", &num) == 1) &&
       (sscanf(argv[2], "%d", &base) == 1) &&
       (0 <= num) &&
       ((2 <= base) && (base <= MAX))) {

       Quack s = createQuack();
       while (num > 0) {
          push(num % base, s);
          num = num / base;
       }
       if (isEmptyQuack(s)) {
          printf("0"); // num was 0
       }
       else {
          while (!isEmptyQuack(s)) {
             int digit = pop(s);
             switch (digit) {
             case 10: putchar('a'); break;
             case 11: putchar('b'); break;
             case 12: putchar('c'); break;
             case 13: putchar('d'); break;
             case 14: putchar('e'); break;
             case 15: putchar('f'); break;
             case 0:case 1: case 2:case 3:case 4:case 5:case 6:case 7:case 8:case 9:
                      printf("%d", digit); break;
             default: printf("Error in conversion\n");
             }
          }
       }
       putchar('\n');
       return EXIT_SUCCESS;
   }
   else {
       printf("Usage: %s number base\n", argv[0]);
       printf("where 2<=base<=%d\n", MAX);
       return EXIT_FAILURE;
   }
}
